### ISSUE TITLE
Can open the link in new tab ?

### ISSUE THREAD

**Issue by Miirwan** [jaketrent/react-social-icons#108]
Hello , 

Is there a way to open the link in new tab when click on icons ?
Thanks!

**Comment by lucaspeferreira** [comment]
Yes, it is! Just pass the prop ```target="_blank"``` within ```<SocialIcon url={telegramShare} />``` component and you're done.

Hope it helps!

**Comment by Miirwan** [comment]
Thank u Lucas that helps me a lot .
