### ISSUE TITLE
v5.10+ background color

### ISSUE THREAD

**Issue by ryancrunchi** [jaketrent/react-social-icons#114]
Since version 5.10, background color seems wrong.
We have options bgColor and fgColor. It seems your internal background component uses fgColor. It should use bgColor.
First because semantically it does not make sense to apply a foreground color to a background.
Second because it is broken. Setting the background color and the icon color the same, make the icon not visible at all, for any color.
If we set fgColor="red", icon is red, background is red...
If we set fgColor="green", icon is green, background is green...
etc...

**Comment by couetilc** [comment]
@ryancrunchi hello can you please post screenshots and some example code so I can reproduce your issues?

**Comment by ryancrunchi** [comment]
Yes sorry, actually it is only with transparent background
You can test here :
https://codesandbox.io/s/admiring-panna-b70lnb?file=/src/App.js

**Comment by asktree** [comment]
I'm still experiencing this issue on 5.13.0 -- transparent bg causes a circle of the foreground color to be rendered, no icon

**Comment by couetilc** [comment]
@asktree please open a new issue and provide a reproduction, preferably with codesandbox, and indicate what icons this happens to. @ryancrunchi reproduction was fixed and is now working (thank you @ryancrunchi for raising this issue)
