### ISSUE TITLE
Icon Request: Xing

### ISSUE THREAD

**Issue by bastiW** [jaketrent/react-social-icons#121]
Xing is the primary business network in Germany, Switzerland and Austria. It would be awesome to have an Icon too. 

Xing has more users in Germany than LinkedIn

https://topdogsocialmedia.com/linkedin-vs-xing/

**Comment by olliglorioso** [comment]
https://github.com/jaketrent/react-social-icons/pull/131
I made a pull request about this. Ich habe dieses Logo hinzugefügt.

**Comment by couetilc** [comment]
@bastiW released in v5.15.0

https://github.com/jaketrent/react-social-icons/releases/tag/v5.15.0
https://www.npmjs.com/package/react-social-icons
