### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ken-salterdiazsolutions** [jaketrent/react-social-icons#149]
I see no updates to issues and no merging of PRs.  Just wondering what the status is.

**Comment by couetilc** [comment]
This project is maintained. I have been busy. I will be merging PRs over next couple of weeks. Thank you for your patience.

**Comment by couetilc** [comment]
@ken-salterdiazsolutions [v6 of react-social-icons](https://www.npmjs.com/package/react-social-icons) has been released, enabling code-splitting, new icons, and other features. See README for more.
