### ISSUE TITLE
Add wee chat

### ISSUE THREAD

**Issue by GustavoRSSilva** [jaketrent/react-social-icons#15]
Is it possible to add a new icon, wechat? It is a very popular Chinese chat application (it is comparable to whatsup).

https://www.google.pt/search?q=wee+chat&source=lnms&tbm=isch&sa=X&ved=0ahUKEwimwdOq3K3TAhVL1xoKHTSJBCIQ_AUICCgB&biw=1855&bih=966

**Comment by jaketrent** [comment]
@GustavoRSSilva yes, it's possible.  Submit a PR, and we can work from that.

**Comment by jaketrent** [comment]
Closing pending pr.
