### ISSUE TITLE
Add Reddit Icon

### ISSUE THREAD

**Issue by dsschapira** [jaketrent/react-social-icons#19]
I think it would be super helpful to add reddit as one of the social networks.  I found where to add this in the code, but I'm not really comfortable enough yet at coming up with the svg code for this.  Would be willing to help out on this if someone could point me towards some helpful documentation on how to get the code for the <svg> and <g> tags.

**Comment by celandro** [comment]
I don't remember where I got it from but I have a reddit svg I use https://static.pokebattler.com/images/reddit.svg

**Comment by jaketrent** [comment]
Merged in another pr.  Closing.
