### ISSUE TITLE
Error @ Social-Icon (ParseDep)

### ISSUE THREAD

**Issue by subsumo** [jaketrent/react-social-icons#2]
I'm getting this error; let me know if there's anything weird happening to you as well.

Error: Parsing file /Users/jacob/Work/ITH001 - IthacaRenting.com/website/custom/themes/ithaca/node_modules/react-social-icons/lib/social-icon.js: Unexpected token (32:6)
    at Deps.parseDeps (/Users/jacob/Work/ITH001 - IthacaRenting.com/website/custom/themes/ithaca/node_modules/browserify/node_modules/module-deps/index.js:436:28)

p.s. sick component.

**Comment by ppiekarczyk** [comment]
I believe it's because there is no compiled version of this project. It uses the spread operator which is only available via Babel

**Comment by jaketrent** [comment]
@subsumo I believe @peterpme is correct.  Now, there should be a compiled/es5 version available from npm since the #4 merge.
