### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by PeterKottas** [jaketrent/react-social-icons#20]
Hi, what would be the recommended way to add hover effect for these icons (change background for example)? Do you have any guidelines?

**Comment by jaketrent** [comment]
No guidelines.  I haven't looked into this lately and am not planning on it.  If you figure it out, I'd love to hear about it or review a PR for it.  Good luck!

**Comment by PeterKottas** [comment]
Yeah I figured, I actually moved to a different lib react-fontawesome in fact. Already got a pro license lying around so why not. I looked at yours as at first it seemed more lightweight but I found a way to only take icons I need from FA so I am happy now

**Comment by haysclark** [comment]
@PeterKottas I have documented a workaround in [Add Icons Color](https://github.com/jaketrent/react-social-icons/issues/18) for changing the colors of the icon. My example includes supporting 'hover' states via CSS.

**Comment by PeterKottas** [comment]
Thanks mate ;)

**Comment by jroller33** [comment]
If you're using react-social-icons v5.15.0 and Tailwind CSS v3.3.2, you can add hover effects to the react social icons like so:
`                url='https://www.youtube.com/username'
                network='youtube'
                fgColor='currentColor'
                bgColor='transparent'
                className='text-gray-500 hover:text-[#ffea00]'`

In this example, the icon is gray with a transparent background, and when you hover it turns yellow with a transparent background.

**Comment by jroller33** [comment]
If you're using react-social-icons v5.15.0 and Tailwind CSS v3.3.2, you can add hover effects to the react social icons like so:

`            <SocialIcon 
                url='https://www.youtube.com/@johnr8729/videos'
                network='youtube'
                fgColor='currentColor'
                bgColor='transparent'
                className='text-gray-500 hover:text-[#ffea00]'
            />
`

In this example, the icon is gray with a transparent background, and when you hover it turns yellow with a transparent background.

**Comment by jroller33** [comment]
If you're using react-social-icons v5.15.0 and Tailwind CSS v3.3.2, you can add hover effects to the react social icons like so:
`
<SocialIcon  
     url='https://www.youtube.com/username' network='youtube' fgColor='currentColor' bgColor='transparent' 
     className='text-gray-500 hover:text-[#ffea00]'
 />
`
In this example, the icon is gray with a transparent background, and when you hover it turns yellow with a transparent background.

**Comment by Elvocool** [comment]
Thank you, this works just fine.
