### ISSUE TITLE
Rename email

### ISSUE THREAD

**Issue by PLoecker** [jaketrent/react-social-icons#21]
I think it is better to rename email. If you use "mailto" it activates the default mail client on the computer.

**Comment by haysclark** [comment]
A rename would cause a regression for users which would not be ideal.  I do think that ```email``` is a very nice term for the icon being used, but it's a shame that the library can not sense the ```mailto:```.

Two possible alternatives:
- Update the REGEX could be updated replace ```mailto``` and replace it with ```email```.
- Add a duplicate DB entry named ```mailto``` that points at ```email``` object?

**Comment by jaketrent** [comment]
published in 2.8.0
