### ISSUE TITLE
Question: setting width and height via CSS

### ISSUE THREAD

**Issue by haysclark** [jaketrent/react-social-icons#23]
Setting the style's _width_ and _height_ to _null_ allows me to use CSS; however, this functionality seems counter-intuitive.

```
<SocialIcon url={url} style={{ width: null, height: null }} />
```
@jaketrent Could you elaborate on the move away from SCSS? I ask because hard-coding the style seems to make the library more difficult to utilize for common scenarios.

**Comment by jaketrent** [comment]
Hey @haysclark , thanks for the question.  Yeah, I wanted the most simple styling story possible in the lib.  So, I used inline js styles.  

If you want to use scss yourself, you can target these elements using the classNames that exist on useful elements.  (eg, `social-container`) If you need another to target, please point it out.
