### ISSUE TITLE
npm install react-social-icons --save-dev requires peer dependencies.

### ISSUE THREAD

**Issue by sajjadpz** [jaketrent/react-social-icons#24]
`npm WARN react-social-icons@2.8.0 requires a peer of react@0.13.x || 0.14.x || 15.x.x but none is installed. You must install peer dependencies yourself.`

where I have installed `"react": "^16.2.0",`, does it work up to 15.x.x only?

**Comment by jaketrent** [comment]
I'll take a look thru the src, but should be ok with react 16 too.  If so, I'll re-release the peerDep spec.

**Comment by jaketrent** [comment]
Now supports react@15 and react@16. Tested in examples page. Released in v2.8.1.
