### ISSUE TITLE
Links to not have discernible (alt) text - Accessibility, and more

### ISSUE THREAD

**Issue by craigatproperly** [jaketrent/react-social-icons#26]
Links produced by the SocialIcons class do not have any text that can be used by screen readers or crawlers.  

Error/resolution description:  https://dequeuniversity.com/rules/axe/2.2/link-name?application=lighthouse 

To reproduce report of the error: 

Any page with SocialIcons react component, run lighthouse audit from chrome developer tools.

**Comment by jaketrent** [comment]
Oh, nice find.  Yes, we'll need to add some readable text.

**Comment by dengeist** [comment]
I was just coming here to report this! Happy to make a PR if that would make your life easier, @jaketrent

**Comment by jaketrent** [comment]
resolved with merge of #27.
