### ISSUE TITLE
Please provide distributed (compiled) file

### ISSUE THREAD

**Issue by peterpme** [jaketrent/react-social-icons#3]
Hi, 

This is a great idea! 

The only issue is that you're using experimental javascript. Most webpack configs will exclude `node_modules` which means this will throw an error.

If you wouldn't mind including a compiled version of this for npm, that would be fantastic!

Thanks

**Comment by jaketrent** [comment]
@peterpme great suggestion.  I believe this is happening now after #4 merge.
