### ISSUE TITLE
will new releases be published to npm?

### ISSUE THREAD

**Issue by thescientist13** [jaketrent/react-social-icons#30]
Just curious if the tags in Github (`2.8.2` and `2.9.0`) will get pushed to npm?  In particular looking to take advantage of these recent changes:
1. [`noopener`](https://github.com/jaketrent/react-social-icons/commit/56b2dee2346387e01646d35c6dc7f713dcb5be38)
1. [`aria-label`](https://github.com/jaketrent/react-social-icons/commit/ccc01b4599b586651bab6a60df91517bced9e4d4#diff-d5a88e3ad82fdc3ea6dd17104fc30f3dR24)

related to #29 

Thanks for all the hard work!

**Comment by jaketrent** [comment]
@thescientist13 thanks for your interest in making sure this gets published.  I just published 2.9.0.  Have a look and let me know if you need anything else.

Also fixed the repo link.  Thanks for the heads up.

**Comment by thescientist13** [comment]
Ah, I see the updated README.md and the new `import` "signature" now, so that has resolved the above error.

It doesn't look like `urls` is supported anymore though?

**Comment by jaketrent** [comment]
agh, yes `SocialIcons` was removed, and yes, I should have bumped to 3.0.0.  I should have looked through the log before I released.  

3.0.0 now pushed.  Sorry. :/

Please just use `SocialIcon` now.  It takes a `url` (singular) prop.  Check the docs page for usage details: https://jaketrent.github.io/react-social-icons/

**Comment by thescientist13** [comment]
thanks so much @jaketrent , keep up the great work!  🙏
