### ISSUE TITLE
How can a user create new icons?

### ISSUE THREAD

**Issue by ml242** [jaketrent/react-social-icons#34]
Hi Jake, 

I would like to make a new object with the mask, icon, and color properties.
Did you use Sketch? It seems that what I get with Photoshop does not play too nicely.

I would like to create an add a Reddit icon to the package.

Thanks for any tips.

**Comment by dctucker** [comment]
Please add a `CONTRIBUTING.md` or augment `README.md` to outlines how to add icons. It seems like it involves adding keys to the exports in `lib/_networks-db.js` but beyond that I'm kinda lost.

**Comment by jaketrent** [comment]
Yes, if someone wants to add this, great.  There have been a few recent icon additions.  In the past, however, people have stumbled over this.  I haven't sourced any in a long time, and how to match the original set is lost to me at the moment.  If someone wants to research and add this to the readme or other docs as suggested, I'd welcome it.
