### ISSUE TITLE
Recommend Stackoverflow Icon

### ISSUE THREAD

**Issue by spina-a-d** [jaketrent/react-social-icons#35]
Seeing as this package that a lot of developers use, I think I could safely recommend the addition of a Stackoverflow icon?

**Comment by jaketrent** [comment]
Yes, SO would be a great add.  Please feel free to open a PR with the new svg paths.  Closing.

**Comment by spina-a-d** [comment]
@jaketrent I'm thinking about handling this soon.  Do you have a stylistic preference for the icons?

**Comment by jaketrent** [comment]
@spina-a-d I'd love it it you added the SO icon.  

A contributor wrote a great little guide to adding the icon:  https://github.com/jaketrent/react-social-icons#contributing

Style-wise, I'd just look for the SO styleguide and try to follow the directions they give there.
