### ISSUE TITLE
Update Instagram logo

### ISSUE THREAD

**Issue by danielcolinjames** [jaketrent/react-social-icons#41]
The Instagram logo included in this library is technically the old one.

It should be updated to match the one they changed to in 2016: https://medium.com/@ianspalter/designing-a-new-look-for-instagram-inspired-by-the-community-84530eb355e3

There should be an SVG here: https://en.instagram-brand.com/assets

I would change it if I knew how but I'm afraid of breaking things 😅

Thank you for this library!

**Comment by jaketrent** [comment]
Hey @danielcolinjames , don't worry about breaking things.  Send a PR, and I'll try it out.  If it works, great.  If not, you are welcome to adjust it.  

There's a nice guide that someone contributed on getting new svgs in there:
https://github.com/jaketrent/react-social-icons#how-to-add-new-icons

**Comment by petercr** [comment]
Hey @jaketrent 👋  I've got an updated version of the Instagram logo ready to go. It's just that it seems to be like... I don't know 20,000 lines of something 🤣 It would sure be a lot cooler if I could just drop in an `svg` because I don't know if all this is gonna fit 😓

**Comment by couetilc** [comment]
addressed in https://github.com/jaketrent/react-social-icons/pull/69
