### ISSUE TITLE
https everywhere

### ISSUE THREAD

**Issue by jimmywarting** [jaketrent/react-social-icons#42]
change the github desc link to use https

http://jaketrent.github.io/react-social-icons/ -> https://jaketrent.github.io/react-social-icons/

**Comment by jaketrent** [comment]
fixed in 3b3925148e5bc888983546e8268382c23f37c613

**Comment by jaketrent** [comment]
Thanks for the comment.

**Comment by jimmywarting** [comment]
Woho, fast!

one left doe 😉 

![skarmavbild 2019-02-08 kl 20 00 28](https://user-images.githubusercontent.com/1148376/52499870-d0f49480-2bdc-11e9-98c9-5a71eaa8d850.png)
