### ISSUE TITLE
Default to target="_blank"

### ISSUE THREAD

**Issue by lethrez** [jaketrent/react-social-icons#43]
Great library & exactly what I was after! (fast and simple)

Just some food for thought, in 99% of cases, I'd want a new tab to open (might just be? am I a tab hoarder?).

Maybe an input parameter that defaults to open new tab might be a good idea?

Happy to write up / add to readme if you think it's a good idea :)

Cheers!

**Comment by jaketrent** [comment]
Yeah, it made sense to me at first as well.  Thanks for your input and willingness to help.

But the default open to _blank has recently been removed by https://github.com/jaketrent/react-social-icons/issues/33

You can still add it as a property if that's what you desire.  

At this point, I think it make sense for this lib to do as little as possible, essentially just providing social svgs.  

Closing for now.

**Comment by lethrez** [comment]
Fair enough, I saw the past #33, was just thinking usage would lean towards this way.

I did implement passing through, just felt like I was passing through much more frequently than not.

Thanks!
