### ISSUE TITLE
Allow support for className?

### ISSUE THREAD

**Issue by bonbonio** [jaketrent/react-social-icons#44]
Hi,

To avoid redundancy, it would be better if we could provide a class that could provide;

height, width, backgroundColor, color, margins, padding

Would avoid repeated code too...

**Comment by couetilc** [comment]
Hi bonbonio, you can provide a class by passing `className` as a prop to the SocialIcon component: `<SocialIcon url="https://www.example.com" className="a-custom-class" />`. This should give you the flexibility to add custom styles and override styles on the child elements. You can also pass a style object using the `style` prop on the SocialIcon component.

React docs for className prop: https://reactjs.org/docs/faq-styling.html
React docs for style prop: https://reactjs.org/docs/dom-elements.html#style
