### ISSUE TITLE
network property is case sensitive

### ISSUE THREAD

**Issue by giuliogallerini** [jaketrent/react-social-icons#47]
The network property is case sensitive so if I insert `YouTube` it's not going to display any logo. Please let me know if I can create a PR for this.

**Comment by couetilc** [comment]
Thank you for raising this issue. Please call [toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) when passing a `network` prop to the SocialIcon component e.g. `<SocialIcon network={'YouTube'.toLowerCase()} />`
