### ISSUE TITLE
npm install not --save-dev

### ISSUE THREAD

**Issue by drood87** [jaketrent/react-social-icons#51]
Hey,

working with gatsby. I saved the package like in the readme documented as a dev dependency but got the error that it should  be saved as a normal dependency, which makes sense I guess?
Or might that be just an error cause I'm working with Gatsby?
Would be crazy if I would be the only one that ran into that issue. Maybe update the Readme.md? I could send a quick PR :)

**Comment by couetilc** [comment]
Thank you for the feedback, addressed in commit https://github.com/jaketrent/react-social-icons/commit/a79657def25e31694ccb95c1ad609617209b9962
