### ISSUE TITLE
size of the icons

### ISSUE THREAD

**Issue by rolandbrake** [jaketrent/react-social-icons#53]
how can I change the size of the icon using CSS

**Comment by ruipsouto** [comment]
You can use inline style, as stated here: [react-social-icons](https://jaketrent.github.io/react-social-icons/)

> ### It scales!
> Witness the beautiful SVG in action.
> Note: this library injects on-page style tags into the head. This is great because you don't have to import any additional stylesheet to support this library. But more specificity in selectors will be required when overriding default styles from external stylesheets.

```
<SocialIcon network="pinterest" style={{ height: 25, width: 25 }} />
<SocialIcon network="pinterest" style={{ height: 50, width: 50 }} />
<SocialIcon network="pinterest" style={{ height: 100, width: 100 }} />
<SocialIcon network="pinterest" style={{ height: 200, width: 200 }} /> 
```
