### ISSUE TITLE
Prop for Opening in a Newtab?

### ISSUE THREAD

**Issue by Suraj-Ram** [jaketrent/react-social-icons#59]
I there a way to open the link (leading to a social page) on a new tab - similar to the ```target="_blank"``` attribute on a ```<a>``` HTML element.

**Comment by danmun** [comment]
It used to be a default until it was [removed](https://github.com/jaketrent/react-social-icons/issues/33#issuecomment-450511445) in 4.1.0.
Usage:
`<SocialIcon url="something" target="_blank" rel="noopener noreferrer" />`

**Comment by couetilc** [comment]
danmun is correct, any props passed to the SocialIcon component will be forwarded to the anchor element wrapping the icon. See https://github.com/jaketrent/react-social-icons/blob/master/src/social-icon.js#L20
