### ISSUE TITLE
[Feature Request] - Website Button

### ISSUE THREAD

**Issue by marcomelilli** [jaketrent/react-social-icons#60]
Is it possible to add a button for a generic website? 🌐

**Comment by couetilc** [comment]
The icon for a generic website is the "Share This" icon. You can see it on the example page where the url prop is `www.example.com`: https://jaketrent.github.io/react-social-icons/

**Comment by couetilc** [comment]
default icon feature added in https://github.com/jaketrent/react-social-icons/commit/6dd83db99e453d4b0f41b9c8adcbfa048c97d401
