### ISSUE TITLE
fork with typescript and optional icons

### ISSUE THREAD

**Issue by MohammedFaragallah** [jaketrent/react-social-icons#68]
@jaketrent  So a while back I forked this project to solve the issue of bundle size.

Today I published this fork with typescript and a context provider you can pass the icons you need only please have a look [HERE](https://github.com/MohammedFaragallah/react-icons-context) and if it interests you I can submit a PR with the changes.

Thank you for this awesome project 🙏

**Comment by couetilc** [comment]
Thank you for your support. I will be closing this PR as I believe the changes are outside the scope of the project for now.
