### ISSUE TITLE
link for someone to email you?

### ISSUE THREAD

**Issue by stephaniezou1** [jaketrent/react-social-icons#70]
Is there a way to have one of the icons lead to a pop up email window? I'm using network="email" to show the icon, but what to place for the URL?

**Comment by couetilc** [comment]
For future reference, set the `url` prop to a [Mailto link](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#e-mail_links)
