### ISSUE TITLE
I think it will be great to have a tiktok icon

### ISSUE THREAD

**Issue by daiky00** [jaketrent/react-social-icons#73]
can we add a tiktok icon for this package?

**Comment by cjfigueiras** [comment]
yes, will be great, I was to use but I need tiktok :-1:

**Comment by CiaranCallaghan94** [comment]
Yes, this will be great.

**Comment by couetilc** [comment]
addressed in https://github.com/jaketrent/react-social-icons/commit/4403cae169aeda790a7c4e09ff9d6d9c422d6a8a
