### ISSUE TITLE
Not working with React 17

### ISSUE THREAD

**Issue by AllAroundD** [jaketrent/react-social-icons#75]
Is this maintained? It seems the React update could have broken the dependency. Would like to know if this will be fixed to work with React 17.

npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x.x || 16.x.x" from react-social-icons@4.1.0
npm ERR! node_modules/react-social-icons
npm ERR!   dev react-social-icons@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ekdnam** [comment]
I am facing the same error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: portfolio@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x.x || 16.x.x" from react-social-icons@4.1.0
npm ERR! node_modules/react-social-icons
npm ERR!   react-social-icons@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by ueabu** [comment]
Running `npm i react-social-icons --legacy-peer-deps` should fix the error for now.

**Comment by AllAroundD** [comment]
ok thank you

**Comment by couetilc** [comment]
addressed in https://github.com/jaketrent/react-social-icons/commit/5e6ea9ce67f921e87a459fb3d636281c254fb219
