### ISSUE TITLE
Interest in ownership?

### ISSUE THREAD

**Issue by jaketrent** [jaketrent/react-social-icons#77]
Hey Internetz, 

Do any of you want to own this library?  I'd love to transfer it to a responsible owner.  

Please respond to this thread with any interest.

Thanks,
Jake

**Comment by couetilc** [comment]
Hi Jake, I'll take it over, I'm planning on using it for a small website and am willing to maintain the repository.

Please let me know how you would like to transfer ownership.

**Comment by jaketrent** [comment]
@couetilc , what's your *npm* username?  I want to add you there so you can get the 5.0 release published when you feel it's ready.

**Comment by couetilc** [comment]
Hi @jaketrent, my npm username is https://www.npmjs.com/~couetilc, thank you. I'll get 5.0 published once the github action for publishing is set up
