### ISSUE TITLE
Discord icon is not appearing

### ISSUE THREAD

**Issue by olivernash** [jaketrent/react-social-icons#84]
Hi - thanks for creating this package. For some reason the Discord icon doesn't seem to appear - all the others I tested are fine.

**Comment by couetilc** [comment]
I cannot reproduce this issue using a `discord.com` url. Can you make sure you are on package version 5+ (`npm i react-social-icons@latest`)? Can you please share your test code and the version number of `react-social-icons` you are using? And include the url and other props you are passing to `<SocialIcon />`?

**Comment by olivernash** [comment]
Thanks @couetilc, it works with the latest version. I thought it might be because the TLD for Discord sharing is .gg - both seem to work now though.

**Comment by couetilc** [comment]
Ok, thank you for following up. I will close this issue, feel free to update with other issues you run into in the future, please just add some example code or a reproducible case.
