### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by hippoboy08** [jaketrent/react-social-icons#89]
I really like this project, and even more if it supports dark mode. Do you have any plan for supporting dark mode icons in the future? Thanks.

**Comment by couetilc** [comment]
@hippoboy08 no plans for dark mode, but would be happy to review any of your contributions. You are able to provide a dark mode for any icons you are using by modifying the `fgColor` and `bgColor` props to your desired color scheme. This repo sets the default colors for an icon to the official brand colors for consistency and identifiability, no consideration is made for dark mode settings.
