### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ozluy** [jaketrent/react-social-icons#9]
Is it possible for you to add [XING](https://www.xing.com) and [Medium](medium.com) icons and list icons names in README file?

**Comment by jaketrent** [comment]
@ozluy Medium is already there with the network id of `medium`.  I'm not too hip on adding Xing, just because I don't feel like it's mainstream enough to include it in everyone's js.

**Comment by jaketrent** [comment]
Closing for now.
