### ISSUE TITLE
Create - Props : target ? target = "_blank" ? Please....

### ISSUE THREAD

**Issue by leandrovitto** [jaketrent/react-social-icons#91]
return _react.default.createElement("a", _extends({}, rest, {
    href: url,
    target : "_blank",
    className: 'social-icon' + (className ? ' ' + className : ''),
    style: _objectSpread({}, _styles.socialIcon, style),
    "aria-label": label || networkKey
 })

**Comment by couetilc** [comment]
@leandrovitto more information please I do not understand your issue?

**Comment by ignasbol** [comment]
@couetilc if I understand correctly, @leandrovitto is referring to making `target = "_blank"` a default (please correct me if I'm wrong). Similar to #43.

Although passing the target as a prop does the trick: `<SocialIcon url="" target="_blank" />`

**Comment by couetilc** [comment]
Thank you @ignasbol for jumping in. @leandrovitto I will not change the default for target, to keep the component as close to the default `<a>` behavior as possible. I recommend creating your own wrapper component in any projects and setting the default target prop there, an example:
```js
// file: MySocialIcon.js
import { SocialIcon } from 'react-social-icons';
export default function MySocialIcon(props) {
  return <SocialIcon target="_blank" {...props} />;
}
```
