### ISSUE TITLE
Feature: Add Clubhouse icon

### ISSUE THREAD

**Issue by styxlab** [jaketrent/react-social-icons#93]
Thanks sow much for this awesome library which I am using in the SaaS Blloging platform [Blogody](https://www.blogody.com).

Some of my users have been requesting a [clubhouse](https://drive.google.com/file/d/1fnqDTH3PbkIwH-GJWmpLxMe273-l5I4c/view) logo. Are you planning to add clubhouse to this library or are you open for pull requests to add this?

**Comment by couetilc** [comment]
Hi @styxlab, feel free to open a PR for creating a clubhouse icon. Follow the directions in the README section for contributing https://github.com/jaketrent/react-social-icons#contributing. I recommend using Inkscape. After you've made the icon, check all tests pass and whether the example site looks good then create the PR. Let me know if you have questions.

**Comment by styxlab** [comment]
Thanks for your prompt reply. Will give it a shot next week.

**Comment by styxlab** [comment]
See #94

**Comment by couetilc** [comment]
addressed in release, v5.6.0, thank you.
